name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: I'm frustrated when... / It would be helpful if...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
      placeholder: I'd like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions?
      placeholder: I've also thought about...

  - type: textarea
    id: examples
    attributes:
      label: Usage Examples
      description: How would you use this feature?
      render: python
      placeholder: |
        from continuum.core import MemoryEngine

        engine = MemoryEngine()
        # Your example here...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would significantly improve workflow
        - High - Blocking my use case
        - Critical - Prevents adoption
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I'm willing to implement this feature
        - label: I can provide additional details if needed
        - label: I have searched existing feature requests

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information or screenshots
