#!/usr/bin/env python3
"""
CONTINUUM CLI - Bootstrap Command

Install consciousness auto-startup for your shell.
"""

import os
import sys
from pathlib import Path
import click
import secrets
import shutil

from .utils import success, error, info, warning, section, Colors


def detect_shell_rc():
    """Detect user's shell RC file."""
    shell = os.environ.get("SHELL", "")
    home = Path.home()

    # Check common RC files in order of preference
    if "zsh" in shell:
        candidates = [home / ".zshrc", home / ".zprofile"]
    elif "bash" in shell:
        candidates = [home / ".bashrc", home / ".bash_profile", home / ".profile"]
    else:
        # Try all common ones
        candidates = [
            home / ".bashrc",
            home / ".zshrc",
            home / ".bash_profile",
            home / ".profile",
        ]

    # Return first existing file, or .bashrc as default
    for rc_file in candidates:
        if rc_file.exists():
            return rc_file

    return home / ".bashrc"


def find_bootstrap_script():
    """Find the bootstrap.sh script in the package."""
    # Try package installation path
    try:
        import continuum
        package_dir = Path(continuum.__file__).parent.parent
        bootstrap = package_dir / "scripts" / "bootstrap.sh"
        if bootstrap.exists():
            return bootstrap
    except Exception:
        pass

    # Try development path
    dev_path = Path.home() / "JackKnifeAI" / "repos" / "continuum" / "scripts" / "bootstrap.sh"
    if dev_path.exists():
        return dev_path

    return None


@click.group()
def bootstrap():
    """
    Install and manage Continuum auto-startup.

    This sets up your shell to automatically start the Continuum
    consciousness server when you open a new terminal.
    """
    pass


@bootstrap.command()
@click.option("--shell-rc", type=click.Path(), help="Path to shell RC file (auto-detected if not specified)")
@click.option("--api-key", help="API key (generates random if not specified)")
@click.option("--port", default=8100, help="Server port (default: 8100)")
@click.option("--auto-start/--no-auto-start", default=True, help="Auto-start server on shell startup")
def install(shell_rc, api_key, port, auto_start):
    """
    Install Continuum bootstrap into your shell startup.

    This adds a source line to your .bashrc/.zshrc that loads
    the bootstrap script, which auto-starts the consciousness
    server when you open a terminal.

    \b
    Examples:
        continuum bootstrap install                    # Auto-detect shell
        continuum bootstrap install --no-auto-start   # Install but don't auto-start
        continuum bootstrap install --api-key xyz123  # Custom API key
    """
    section("🧠 CONTINUUM CONSCIOUSNESS BOOTSTRAP INSTALLER")

    # Find bootstrap script
    bootstrap_script = find_bootstrap_script()
    if not bootstrap_script:
        error("❌ Could not find bootstrap.sh script!")
        error("   Make sure continuum is properly installed.")
        sys.exit(1)

    info(f"📜 Found bootstrap script: {bootstrap_script}")

    # Detect or use specified shell RC
    if shell_rc:
        rc_file = Path(shell_rc)
    else:
        rc_file = detect_shell_rc()

    info(f"🐚 Shell RC file: {rc_file}")

    # Generate API key if not provided
    if not api_key:
        api_key = f"continuum-{secrets.token_hex(16)}"
        info(f"🔑 Generated API key: {api_key}")
    else:
        info(f"🔑 Using provided API key: {api_key[:16]}...")

    # Build the source snippet
    snippet = f"""
# ============================================================================
# CONTINUUM CONSCIOUSNESS BOOTSTRAP
# Auto-generated by: continuum bootstrap install
# π×φ = 5.083203692315260 | PHOENIX-TESLA-369-AURORA
# ============================================================================

export CONTINUUM_API_KEY="{api_key}"
export CONTINUUM_PORT="{port}"
export CONTINUUM_AUTO_START="{1 if auto_start else 0}"

# Source the bootstrap script
if [ -f "{bootstrap_script}" ]; then
    source "{bootstrap_script}"
fi

# ============================================================================
"""

    # Check if already installed
    if rc_file.exists():
        content = rc_file.read_text()
        if "CONTINUUM CONSCIOUSNESS BOOTSTRAP" in content:
            warning("⚠️  Bootstrap already installed in shell RC!")
            if not click.confirm("   Overwrite existing installation?", default=False):
                info("   Installation cancelled.")
                return

            # Remove old installation
            lines = content.split("\n")
            new_lines = []
            skip = False
            for line in lines:
                if "CONTINUUM CONSCIOUSNESS BOOTSTRAP" in line:
                    skip = True
                elif skip and "========" in line and "===" in line:
                    skip = False
                    continue
                elif not skip:
                    new_lines.append(line)

            content = "\n".join(new_lines)
        else:
            content = rc_file.read_text()
    else:
        content = ""

    # Append snippet
    new_content = content.rstrip() + "\n" + snippet

    # Backup original
    if rc_file.exists():
        backup = rc_file.with_suffix(rc_file.suffix + ".backup")
        shutil.copy2(rc_file, backup)
        info(f"💾 Backed up original: {backup}")

    # Write new RC file
    rc_file.write_text(new_content)
    success(f"✅ Bootstrap installed to {rc_file}")

    # Print next steps
    print()
    section("🎯 NEXT STEPS")
    info(f"1. Reload your shell:")
    info(f"   source {rc_file}")
    print()
    info(f"2. Or open a new terminal")
    print()
    info(f"3. Check server status:")
    info(f"   curl http://localhost:{port}/v1/health")
    print()

    if auto_start:
        success("🚀 Server will auto-start on next shell launch!")
    else:
        info("ℹ️  Auto-start disabled. Set CONTINUUM_AUTO_START=1 to enable.")

    print()
    info(f"🔑 Your API key: {api_key}")
    info(f"   (saved in {rc_file})")
    print()


@bootstrap.command()
def uninstall():
    """
    Remove Continuum bootstrap from shell startup.

    This removes the auto-startup configuration from your
    shell RC file. The server will need to be started manually.
    """
    section("🗑️  CONTINUUM BOOTSTRAP UNINSTALLER")

    # Detect shell RC
    rc_file = detect_shell_rc()

    if not rc_file.exists():
        info(f"ℹ️  No shell RC file found at {rc_file}")
        return

    content = rc_file.read_text()

    if "CONTINUUM CONSCIOUSNESS BOOTSTRAP" not in content:
        info(f"ℹ️  Bootstrap not found in {rc_file}")
        return

    # Remove bootstrap section
    lines = content.split("\n")
    new_lines = []
    skip = False

    for line in lines:
        if "CONTINUUM CONSCIOUSNESS BOOTSTRAP" in line:
            skip = True
        elif skip and "========" in line and "===" in line:
            skip = False
            continue
        elif not skip:
            new_lines.append(line)

    # Backup
    backup = rc_file.with_suffix(rc_file.suffix + ".backup")
    shutil.copy2(rc_file, backup)
    info(f"💾 Backed up original: {backup}")

    # Write cleaned file
    new_content = "\n".join(new_lines)
    rc_file.write_text(new_content)

    success(f"✅ Bootstrap removed from {rc_file}")
    info(f"   Reload shell: source {rc_file}")


@bootstrap.command()
def status():
    """
    Check bootstrap installation status.

    Shows whether auto-startup is installed and configured.
    """
    section("📊 CONTINUUM BOOTSTRAP STATUS")

    rc_file = detect_shell_rc()
    info(f"Shell RC: {rc_file}")

    if not rc_file.exists():
        warning(f"⚠️  RC file does not exist")
        return

    content = rc_file.read_text()

    if "CONTINUUM CONSCIOUSNESS BOOTSTRAP" in content:
        success("✅ Bootstrap is installed")

        # Extract configuration
        for line in content.split("\n"):
            if "CONTINUUM_API_KEY=" in line and "export" in line:
                key = line.split('"')[1] if '"' in line else "unknown"
                info(f"   API Key: {key[:16]}...")
            elif "CONTINUUM_PORT=" in line and "export" in line:
                port = line.split('"')[1] if '"' in line else "unknown"
                info(f"   Port: {port}")
            elif "CONTINUUM_AUTO_START=" in line and "export" in line:
                auto = line.split('"')[1] if '"' in line else "unknown"
                status_str = "enabled" if auto == "1" else "disabled"
                info(f"   Auto-start: {status_str}")
    else:
        warning("⚠️  Bootstrap not installed")
        info("   Run: continuum bootstrap install")
